moar CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,186 +23,185 @@ env:
 
 
 jobs:
-  # test:
-  #   name: Run pre commit checks and tests
-  #   runs-on: [self-hosted, zurich]
-  #   timeout-minutes: 30
+  test:
+    name: Run pre commit checks and tests
+    runs-on: [self-hosted, zurich]
+    timeout-minutes: 30
 
-  #   container:
-  #     image: nvcr.io/nvstaging/isaac-amr/isaac_arena:latest
-  #     credentials:
-  #       username: $oauthtoken
-  #       password: ${{ env.NGC_API_KEY }}
+    container:
+      image: nvcr.io/nvstaging/isaac-amr/isaac_arena:latest
+      credentials:
+        username: $oauthtoken
+        password: ${{ env.NGC_API_KEY }}
 
-  #   steps:
-  #     - name: Install git (and tools needed by hooks)
-  #       run: |
-  #         apt-get update
-  #         apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates
-  #         git --version
-  #         git lfs version
+    steps:
+      - name: Install git (and tools needed by hooks)
+        run: |
+          apt-get update
+          apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates
+          git --version
+          git lfs version
 
-  #     # Checkout Code
-  #     - name: Checkout Code
-  #       uses: actions/checkout@v4
-  #       with:
-  #         clean: true
-  #         fetch-depth: 0
-  #         # LFS checkout here somehow causes issues when LFS stuff changes over time.
-  #         # So I do LFS manually in a step after.
-  #         # lfs: true
+      # Checkout Code
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          clean: true
+          fetch-depth: 0
+          # LFS checkout here somehow causes issues when LFS stuff changes over time.
+          # So I do LFS manually in a step after.
+          # lfs: true
 
-  #     # Fix "detected dubious ownership in repository" inside containers
-  #     - name: Mark repo as safe for git
-  #       run: git config --global --add safe.directory "$PWD"
+      # Fix "detected dubious ownership in repository" inside containers
+      - name: Mark repo as safe for git
+        run: git config --global --add safe.directory "$PWD"
 
-  #     # Pull LFS files explicitly (in case checkout didn't get them all)
-  #     - name: Git LFS
-  #       run: |
-  #         git lfs update --force
-  #         git lfs install --local
-  #         git lfs pull
+      # Pull LFS files explicitly (in case checkout didn't get them all)
+      - name: Git LFS
+        run: |
+          git lfs update --force
+          git lfs install --local
+          git lfs pull
 
-  #     - name: Setup Python
-  #       uses: actions/setup-python@v3
+      - name: Setup Python
+        uses: actions/setup-python@v3
 
-  #     - name: Install project and link isaac-sim
-  #       run: |
-  #         pip install --no-cache-dir -e .
-  #         [ -e ./submodules/IsaacLab/_isaac_sim ] || ln -s /isaac-sim ./submodules/IsaacLab/_isaac_sim
+      - name: Install project and link isaac-sim
+        run: |
+          pip install --no-cache-dir -e .
+          [ -e ./submodules/IsaacLab/_isaac_sim ] || ln -s /isaac-sim ./submodules/IsaacLab/_isaac_sim
 
-  #     - name: Run pre-commit
-  #       run: |
-  #         pip install --no-cache-dir --upgrade pip pre-commit
-  #         pre-commit run --all-files
+      - name: Run pre-commit
+        run: |
+          pip install --no-cache-dir --upgrade pip pre-commit
+          pre-commit run --all-files
 
-  #     - name: Run pytest excluding policy-related tests
-  #       run: /isaac-sim/python.sh -m pytest -sv isaac_arena/tests/ --ignore=isaac_arena/tests/policy/
+      - name: Run pytest excluding policy-related tests
+        run: /isaac-sim/python.sh -m pytest -sv isaac_arena/tests/ --ignore=isaac_arena/tests/policy/
 
-  # TODO(Vik): Reanable test
-  # test_policy:
-  #   name: Run policy-related tests with GR00T & cuda12_8 deps
-  #   runs-on: [self-hosted, zurich]
-  #   timeout-minutes: 30
+  TODO(Vik): Reanable test
+  test_policy:
+    name: Run policy-related tests with GR00T & cuda12_8 deps
+    runs-on: [self-hosted, zurich]
+    timeout-minutes: 30
 
-  #   container:
-  #     image: nvcr.io/nvstaging/isaac-amr/isaac_arena:cuda_gr00t
-  #     credentials:
-  #       username: $oauthtoken
-  #       password: ${{ env.NGC_API_KEY }}
-  #     # virtual mounted checkpoints directory from the local machine
-  #     volumes:
-  #       - /home/runner/checkpoints:/checkpoints
-  #   steps:
-  #     - name: Print checkpoints directory
-  #       run: ls -la /checkpoints
+    container:
+      image: nvcr.io/nvstaging/isaac-amr/isaac_arena:cuda_gr00t
+      credentials:
+        username: $oauthtoken
+        password: ${{ env.NGC_API_KEY }}
+      # virtual mounted checkpoints directory from the local machine
+      volumes:
+        - /home/runner/checkpoints:/checkpoints
+    steps:
+      - name: Print checkpoints directory
+        run: ls -la /checkpoints
 
-  #     - name: Install git (and tools needed by hooks)
-  #       run: |
-  #         apt-get update
-  #         apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates
-  #         git --version
-  #         git lfs version
+      - name: Install git (and tools needed by hooks)
+        run: |
+          apt-get update
+          apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates
+          git --version
+          git lfs version
 
-  #     # Checkout Code
-  #     - name: Checkout Code
-  #       uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
-  #         # LFS checkout here somehow causes issues when LFS stuff changes over time.
-  #         # So I do LFS manually in a step after.
-  #         # lfs: true
+      # Checkout Code
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          # LFS checkout here somehow causes issues when LFS stuff changes over time.
+          # So I do LFS manually in a step after.
+          # lfs: true
 
-  #     # Fix "detected dubious ownership in repository" inside containers
-  #     - name: Mark repo as safe for git
-  #       run: git config --global --add safe.directory "$PWD"
+      # Fix "detected dubious ownership in repository" inside containers
+      - name: Mark repo as safe for git
+        run: git config --global --add safe.directory "$PWD"
 
-  #     # Pull LFS files explicitly (in case checkout didn't get them all)
-  #     - name: Git LFS
-  #       run: |
-  #         git lfs update --force
-  #         git lfs install --local
-  #         git lfs pull
+      # Pull LFS files explicitly (in case checkout didn't get them all)
+      - name: Git LFS
+        run: |
+          git lfs update --force
+          git lfs install --local
+          git lfs pull
 
-  #     - name: Setup Python
-  #       uses: actions/setup-python@v3
+      - name: Setup Python
+        uses: actions/setup-python@v3
 
-  #     - name: Install project and link isaac-sim
-  #       run: |
-  #         pip install --no-cache-dir -e .
-  #         [ -e ./submodules/IsaacLab/_isaac_sim ] || ln -s /isaac-sim ./submodules/IsaacLab/_isaac_sim
+      - name: Install project and link isaac-sim
+        run: |
+          pip install --no-cache-dir -e .
+          [ -e ./submodules/IsaacLab/_isaac_sim ] || ln -s /isaac-sim ./submodules/IsaacLab/_isaac_sim
 
-  #     - name: Run policy-related pytest
-  #       run: /isaac-sim/python.sh -m pytest -sv isaac_arena/tests/policy/
+      - name: Run policy-related pytest
+        run: /isaac-sim/python.sh -m pytest -sv isaac_arena/tests/policy/
 
 
-  # build_and_push_image_post_merge:
-  #   name: Build & push NGC image (post-merge)
-  #   runs-on: [self-hosted, zurich]
-  #   timeout-minutes: 60
-  #   needs: [test]       # only push if tests passed
-  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+  build_and_push_image_post_merge:
+    name: Build & push NGC image (post-merge)
+    runs-on: [self-hosted, zurich]
+    timeout-minutes: 60
+    needs: [test]       # only push if tests passed
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 
-  #   container:
-  #     image: ubuntu:latest
+    container:
+      image: ubuntu:latest
 
-  #   env:
-  #     # already defined at top, but keep here for clarity/local override if needed
-  #     NGC_API_KEY: ${{ secrets.ARENA_NGC_API_KEY }}
+    env:
+      # already defined at top, but keep here for clarity/local override if needed
+      NGC_API_KEY: ${{ secrets.ARENA_NGC_API_KEY }}
 
-  #   steps:
-  #     - name: Install git (and tools needed by hooks)
-  #       run: |
-  #         apt-get update
-  #         apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates
-  #         git --version
-  #         git lfs version
+    steps:
+      - name: Install git (and tools needed by hooks)
+        run: |
+          apt-get update
+          apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates
+          git --version
+          git lfs version
 
-  #     # Fix "detected dubious ownership in repository" inside containers
-  #     - name: Mark repo as safe for git
-  #       run: git config --global --add safe.directory "$PWD"
+      # Fix "detected dubious ownership in repository" inside containers
+      - name: Mark repo as safe for git
+        run: git config --global --add safe.directory "$PWD"
 
-  #     # Somehow this simlink remains from the previous steps, and it causes the submodule
-  #     # checkout to fail. So here we clean it up, before checking out the submodules.
-  #     - name: cleanup IsaacSim simlink
-  #       run: rm -f submodules/IsaacLab/_isaac_sim
+      # Somehow this simlink remains from the previous steps, and it causes the submodule
+      # checkout to fail. So here we clean it up, before checking out the submodules.
+      - name: cleanup IsaacSim simlink
+        run: rm -f submodules/IsaacLab/_isaac_sim
 
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
-  #         lfs: true
-  #         submodules: true
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          lfs: true
+          submodules: true
 
-  #     - name: submodules
-  #       run: git submodule update --init
+      - name: submodules
+        run: git submodule update --init
 
-  #     - name: Install docker
-  #       run: |
-  #         apt-get update
-  #         apt-get install -y ca-certificates curl gnupg && \
-  #         install -m 0755 -d /etc/apt/keyrings && \
-  #         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
-  #         chmod a+r /etc/apt/keyrings/docker.gpg && \
-  #         echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
-  #         "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null &&
-  #         apt-get update && apt-get install -y docker.io docker-buildx-plugin
-  #         docker --version
+      - name: Install docker
+        run: |
+          apt-get update
+          apt-get install -y ca-certificates curl gnupg && \
+          install -m 0755 -d /etc/apt/keyrings && \
+          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
+          chmod a+r /etc/apt/keyrings/docker.gpg && \
+          echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+          "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null &&
+          apt-get update && apt-get install -y docker.io docker-buildx-plugin
+          docker --version
 
-  #     - name: Docker login to NGC
-  #       # $oauthtoken is the literal NGC username; pipe the NGC API key via stdin
-  #       run: echo "${NGC_API_KEY}" | docker login nvcr.io -u '$oauthtoken' --password-stdin
+      - name: Docker login to NGC
+        # $oauthtoken is the literal NGC username; pipe the NGC API key via stdin
+        run: echo "${NGC_API_KEY}" | docker login nvcr.io -u '$oauthtoken' --password-stdin
 
-  #     - name: Build & push image to NGC
-  #       run: |
-  #         chmod +x ./docker/push_to_ngc* || true
-  #         ./docker/push_to_ngc.sh -p
+      - name: Build & push image to NGC
+        run: |
+          chmod +x ./docker/push_to_ngc* || true
+          ./docker/push_to_ngc.sh -p
 
-  #     - name: Build & push image to NGC (GR00T Image)
-  #       run: |
-  #         chmod +x ./docker/push_to_ngc* || true
-  #         ./docker/push_to_ngc.sh -p -g -t cuda_gr00t
-
+      - name: Build & push image to NGC (GR00T Image)
+        run: |
+          chmod +x ./docker/push_to_ngc* || true
+          ./docker/push_to_ngc.sh -p -g -t cuda_gr00t
 
 
   docs_pre_merge:
@@ -234,27 +233,4 @@ jobs:
           cd docs
           pip3 install -r requirements.txt
           make SPHINXOPTS=-W html
-          touch ./_build/html/.nojekyll 
-
-      # Deploy to pages
-      # Deploying is as simple as copying the index.html file to the root of the repository
-      # Note that by default GitHub pages will assume that this is a Jekyll site, so we need to
-      # create a .nojekyll file to disable Jekyll.
-      # - name: Deploy to GitHub Pages
-      #   run: |
-      #     cp -r docs/_build/html/* docs/
-      #     touch docs/.nojekyll 
-
-      - name: Upload static files as artifact
-        id: deployment
-        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
-        with:
-          path: docs/_build/html/
-
-
-
-      # - name: Deploy to GitHub Pages
-      #   uses: peaceiris/actions-gh-pages@v4
-      #   with:
-      #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      #     publish_dir: ./_build/html
+          touch ./_build/html/.nojekyll
