CI: Add yaml anchors to remove repetition in ci workflow (#245)
## Summary
Add yaml anchors to remove repetition in ci workflow.

## Detailed description
- We have several jobs in our workflow which share common steps.
- This MR eliminates the repetition of those steps by using yaml
anchors.
- In some cases small differences in the steps were eliminated by
unifying the steps.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,38 +40,53 @@ jobs:
         password: ${{ env.NGC_API_KEY }}
 
     steps:
-      - name: Install git (and tools needed by hooks)
+      - &install_git_step
+        name: Install git (and tools needed by hooks)
         run: |
           apt-get update
-          apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates
+          apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates make
           git --version
           git lfs version
 
+      # Clean up residual stuff due to symlinks in the submodules directory
+      # We do this prior to checkout because the symlink causes issues if it's there from a previous run.
+      - &cleanup_step
+        name: Clean up symlinks in submodules directory
+        run: |
+          rm -f .git/modules/submodules/IsaacLab/index.lock || true
+          rm -rf submodules/IsaacLab || true
+
       # Checkout Code
-      - name: Checkout Code
+      - &checkout_step
+        name: Checkout Code
         uses: actions/checkout@v4
         with:
-          clean: true
           fetch-depth: 0
+          clean: true
+          submodules: true
           # LFS checkout here somehow causes issues when LFS stuff changes over time.
           # So I do LFS manually in a step after.
           # lfs: true
 
       # Fix "detected dubious ownership in repository" inside containers
-      - name: Mark repo as safe for git
+      - &mark_repo_safe_step
+        name: Mark repo as safe for git
         run: git config --global --add safe.directory "$PWD"
 
       # Pull LFS files explicitly (in case checkout didn't get them all)
-      - name: Git LFS
+      - &git_lfs_step
+        name: Git LFS
         run: |
           git lfs update --force
           git lfs install --local
           git lfs pull
 
-      - name: Setup Python
+      - &setup_python_step
+        name: Setup Python
         uses: actions/setup-python@v3
 
-      - name: Install project and link isaac-sim
+      - &install_project_step
+        name: Install project and link isaac-sim
         run: |
           pip install --no-cache-dir -e .
           [ -e ./submodules/IsaacLab/_isaac_sim ] || ln -s /isaac-sim ./submodules/IsaacLab/_isaac_sim
@@ -87,7 +102,6 @@ jobs:
       - name: Run pytest excluding policy-related tests. Now we run all tests with cameras.
         run: /isaac-sim/python.sh -m pytest -sv -m with_cameras isaaclab_arena/tests/ --ignore=isaaclab_arena/tests/policy/
 
-
   test_policy:
     name: Run policy-related tests with GR00T & cuda12_8 deps
     runs-on: [self-hosted, zurich]
@@ -102,43 +116,17 @@ jobs:
       volumes:
         - /home/runner/checkpoints:/checkpoints
     steps:
+      # Setup.
+      - *install_git_step
+      - *cleanup_step
+      - *checkout_step
+      - *mark_repo_safe_step
+      - *git_lfs_step
+      - *setup_python_step
+      - *install_project_step
+
       - name: Print checkpoints directory
         run: ls -la /checkpoints
-
-      - name: Install git (and tools needed by hooks)
-        run: |
-          apt-get update
-          apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates
-          git --version
-          git lfs version
-
-      # Checkout Code
-      - name: Checkout Code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          # LFS checkout here somehow causes issues when LFS stuff changes over time.
-          # So I do LFS manually in a step after.
-          # lfs: true
-
-      # Fix "detected dubious ownership in repository" inside containers
-      - name: Mark repo as safe for git
-        run: git config --global --add safe.directory "$PWD"
-
-      # Pull LFS files explicitly (in case checkout didn't get them all)
-      - name: Git LFS
-        run: |
-          git lfs update --force
-          git lfs install --local
-          git lfs pull
-
-      - name: Setup Python
-        uses: actions/setup-python@v3
-
-      - name: Install project and link isaac-sim
-        run: |
-          pip install --no-cache-dir -e .
-          [ -e ./submodules/IsaacLab/_isaac_sim ] || ln -s /isaac-sim ./submodules/IsaacLab/_isaac_sim
 
       - name: Run policy-related pytest
         run: /isaac-sim/python.sh -m pytest -sv isaaclab_arena/tests/policy/
@@ -152,19 +140,10 @@ jobs:
       image: python:3.11-slim
 
     steps:
-      - name: Install git (and tools needed by hooks)
-        run: |
-          apt-get update
-          apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates make
-          git --version
-          git lfs version
-
-      # Checkout Code
-      - name: Checkout Code
-        uses: actions/checkout@v4
-        with:
-          clean: true
-          fetch-depth: 0
+      # Setup.
+      - *install_git_step
+      - *cleanup_step
+      - *checkout_step
 
       # Build docs
       - name: Build docs
@@ -189,31 +168,11 @@ jobs:
       NGC_API_KEY: ${{ secrets.ARENA_NGC_API_KEY }}
 
     steps:
-      - name: Install git (and tools needed by hooks)
-        run: |
-          apt-get update
-          apt-get install -y --no-install-recommends git git-lfs clang-format ca-certificates
-          git --version
-          git lfs version
-
-      # Fix "detected dubious ownership in repository" inside containers
-      - name: Mark repo as safe for git
-        run: git config --global --add safe.directory "$PWD"
-
-      # Somehow this simlink remains from the previous steps, and it causes the submodule
-      # checkout to fail. So here we clean it up, before checking out the submodules.
-      - name: cleanup IsaacSim simlink
-        run: rm -f submodules/IsaacLab/_isaac_sim
-
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          lfs: true
-          submodules: true
-
-      - name: submodules
-        run: git submodule update --init
+      # Setup.
+      - *install_git_step
+      - *mark_repo_safe_step
+      - *cleanup_step
+      - *checkout_step
 
       - name: Install docker
         run: |
