WIP

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -207,49 +207,49 @@ jobs:
           make SPHINXOPTS=-W html
           touch ./_build/html/.nojekyll
 
-  build_and_push_image_post_merge:
-    name: Build & push NGC image (post-merge)
-    runs-on: [self-hosted, zurich]
-    timeout-minutes: 60
-    needs: [test, test_policy, build_docs_pre_merge]       # only push if tests passed
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+  # build_and_push_image_post_merge:
+  #   name: Build & push NGC image (post-merge)
+  #   runs-on: [self-hosted, zurich]
+  #   timeout-minutes: 60
+  #   needs: [test, test_policy, build_docs_pre_merge]       # only push if tests passed
+  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 
-    container:
-      image: ubuntu:latest
+  #   container:
+  #     image: ubuntu:latest
 
-    env:
-      # already defined at top, but keep here for clarity/local override if needed
-      NGC_API_KEY: ${{ secrets.ARENA_NGC_API_KEY }}
+  #   env:
+  #     # already defined at top, but keep here for clarity/local override if needed
+  #     NGC_API_KEY: ${{ secrets.ARENA_NGC_API_KEY }}
 
-    steps:
-      # Setup.
-      - *install_git_step
-      - *mark_repo_safe_step
-      - *cleanup_step
-      - *checkout_step
+  #   steps:
+  #     # Setup.
+  #     - *install_git_step
+  #     - *mark_repo_safe_step
+  #     - *cleanup_step
+  #     - *checkout_step
 
-      - name: Install docker
-        run: |
-          apt-get update
-          apt-get install -y ca-certificates curl gnupg && \
-          install -m 0755 -d /etc/apt/keyrings && \
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
-          chmod a+r /etc/apt/keyrings/docker.gpg && \
-          echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
-          "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null &&
-          apt-get update && apt-get install -y docker.io docker-buildx-plugin
-          docker --version
+  #     - name: Install docker
+  #       run: |
+  #         apt-get update
+  #         apt-get install -y ca-certificates curl gnupg && \
+  #         install -m 0755 -d /etc/apt/keyrings && \
+  #         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
+  #         chmod a+r /etc/apt/keyrings/docker.gpg && \
+  #         echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
+  #         "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null &&
+  #         apt-get update && apt-get install -y docker.io docker-buildx-plugin
+  #         docker --version
 
-      - name: Docker login to NGC
-        # $oauthtoken is the literal NGC username; pipe the NGC API key via stdin
-        run: echo "${NGC_API_KEY}" | docker login nvcr.io -u '$oauthtoken' --password-stdin
+  #     - name: Docker login to NGC
+  #       # $oauthtoken is the literal NGC username; pipe the NGC API key via stdin
+  #       run: echo "${NGC_API_KEY}" | docker login nvcr.io -u '$oauthtoken' --password-stdin
 
-      - name: Build & push image to NGC
-        run: |
-          chmod +x ./docker/push_to_ngc* || true
-          ./docker/push_to_ngc.sh -p
+  #     - name: Build & push image to NGC
+  #       run: |
+  #         chmod +x ./docker/push_to_ngc* || true
+  #         ./docker/push_to_ngc.sh -p
 
-      - name: Build & push image to NGC (GR00T Image)
-        run: |
-          chmod +x ./docker/push_to_ngc* || true
-          ./docker/push_to_ngc.sh -p -g -t cuda_gr00t
+  #     - name: Build & push image to NGC (GR00T Image)
+  #       run: |
+  #         chmod +x ./docker/push_to_ngc* || true
+  #         ./docker/push_to_ngc.sh -p -g -t cuda_gr00t
